default_settings: null
behaviors:
  PoliceAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 51200
      learning_rate: 0.0003
      beta: 0.007
      epsilon: 0.3
      lambd: 0.97
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.97
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 512
          num_layers: 3
      curiosity:
        gamma: 0.97
        strength: 0.05
        learning_rate: 0.0003
        network_settings:
          normalize: true
          hidden_units: 512
          num_layers: 3
    init_path: null
    keep_checkpoints: 20
    checkpoint_interval: 5000000
    max_steps: 150000000
    time_horizon: 64
    summary_freq: 10000
env_settings: 
  base_port: 5005
  num_envs: 4
  num_areas: 256
  seed: 7777
engine_settings:
  width: 1920
  height: 1080
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
checkpoint_settings:
  run_id: ppo
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false
